

import 'package:get/get_navigation/src/root/internacionalization.dart';

class languages extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {

    'en_US' : {

      'appbarTitle': 'Yuva Sathi',
      'gov_up': 'Government of Uttar Pradesh',
      'welcom': 'Welcome to',
      'logobottom': 'Partner of success young friend !',
      'sanghtext': 'Youth Welfare and \nPrantiya Rakshak Dal Department',
      'sanghtexts': 'Youth Welfare and Prantiya Rakshak Dal Department',
      'exploremodule': 'EXPLORE THE MODULES',
      'appbarSecondTitle': 'Stop searching, start discovering! Register today on Yuva sathi portal and unlock a world of incredible schemes just for you.',
      'backButton': 'Back',
      'by': 'By',
      'step1': 'STEP 1',
      'step2': 'STEP 2',
      'step3': 'STEP 3',
      'step4': 'STEP 4',
      'step5': 'STEP 5',
      'step6': 'STEP 6',
      'step7': 'STEP 7',
      'step8': 'STEP 8',

      'fcstep1': 'Youth to enter mobile number for registration',
      'fcstep2': 'OTP Verification',
      'fcstep3': 'Profile creation of youth',
      'fcstep4': 'Get basic information of youth like Name, Age, Sex, Religion, Caste, Marital Status, Qualification, Specialization, Job Status, Experience, Scholarships, Awards, others',
      'fcstep5': 'Youth to select their interests/skills and fill their requirement',
      'fcstep6': 'Youth will get suggestions of Government schemes as per their selected interest',
      'fcstep7': 'Youth to be redirected to concern department portal for applying schemes/services',
      'fcstep8': 'Analytics & MIS report to be provided to state government',

      'step1subheading': 'Register by filling details such as Name and Mobile number where  receive an OTP for verification.',
      'step2subheading': 'Provide us with some information about yourself',
      'step3subheading': 'Get scheme recommendations for your chosen skills',
      'step4subheading': 'Personalize your experience. Choose your district to proceed',
      'step5subheading': '',
      'step6subheading': 'Help us to Map Your Career Landscape',
      'step7subheading': 'Help us to Map Your Career Landscape',
      'step8subheading': '',
      'searchCardsubheading': 'Explore the goverment schemes/services',

      'profitsubappbarheading': 'Registration of Youth for the purpose of getting information about their requirement, interests, and skills to provide them benefits accordingly',
      'singupheading':'Unlock the best schemes for your needs through a very simple registration process',
      'step1heading': 'Unlock the best schemes for your needs through a very simple registration process',
      'step2heading': 'Introduce yourself!\nWe want to know more about you.',
      'step3heading': 'Get scheme information for the skills you are passionate about',
      'step4heading': 'Find district-specific details by selecting your location',
      'step5heading': 'Which caste system do you belong to?',
      'step6heading': 'Exploring Your Current Employment Status',
      'step7heading': 'Express your last Qualification',
      'step8heading': 'Explore Your Eligibility: Select Categories to Discover Available Schemes',
      'searchCardheading': 'Goverment Department Schemes for youth',

      'schemes1': 'Education & Scholarship',
      'schemes2': 'Business & Entrepreneurship',
      'schemes3': 'Skill Development',
      'schemes4': 'Sport & Culture',
      'schemes5': 'Employment',
      'schemes6': 'Empowerment',
      'schemes7': 'Housing & Shelter',
      'schemes8': 'Financial Services',
      'schemes9': 'Socio-Economic',
      'schemes10': 'Health & Wellness',
      'warningtoast': 'Proper Fill the Information',
      'rightsteptoast': 'This Step Completed Successfully',
      'loginSuccessptoast': 'Login Successfull',
      'otpSuccessptoast': 'OTP Send Succesfully',
      'registerSuccessptoast': 'Registration Successfully',
      'successptoast': 'Successfull',
      'submittext': 'Submit',
      'resetPassword': 'Reset Password',
      'getOTP': 'After Getting OTP? ',
      'other': 'Others',
      'tenth': '10th Grade',
      'twelvth': 'Intermediate',
      'graduation': 'Graduate',
      'pgraduation': 'Post Graduate',
      'next': 'Next',
      'step7SEThint': 'Enter Qualification Name',
      'status1': 'Employed',
      'status2': 'Unemployed',
      'status3': 'Self Employed',
      'status4': 'Entrepreneur',
      'status5': 'Student',
      'sendotp': 'Send OTP',
      'register': 'Register',
      'registration': 'Registration',
      'noaccount': 'Do not have an account? ',
      'ifregisterthenlogin': 'If already have a registered? ',
      'login': 'LOGIN',
      'loginSmall': 'Login',
      'onlylogin': 'LOGIN',
      'nameEditText': 'Enter Name',
      'mobileEditText': 'Enter Mobile Number',
      'passwordEditText': 'Enter Password',
      'emailEditText': 'Enter Email',
      'subjectEditText': 'Enter Subject',
      'msgEditText': 'Enter Message',
      'cpasswordEditText': 'Confirm Password',
      'otpEditText': 'Enter Verification Code',
      'otpNoText': 'An authentication code will be sent to your this number',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'age': 'Age',
      'ageEditText': 'Enter Age',
      'selectSkill': 'Select Skill',
      'selectdistrict': 'Select District',
      'placeType': 'Specify your location type',
      'rural': 'Rural',
      'arban': 'Urban',
      'rl&rbn':'Rural-Urban',
      'castEditText': 'Enter Other Caste Name',
      'cast1': 'General',
      'cast2': 'Other Backward Class (OBC)',
      'cast3': 'Scheduled Caste (SC)',
      'cast4': 'Scheduled Tribe (ST)',
      'helpLineHeading': 'We’re always available for your support! Contact to require a detailed information',
      'helpLineSubHeading': 'Help Desk Number  +91-9005604448',
      'footerHeading': 'A Single Platform for Youth of Uttar Pradesh to get information related to Jobs, Skill development, Vocational Training, Employment, Self-Employment, Higher Education, Competitive Examination, Carrier Counselling, Sports, Health, Secondary Education, Start-Up, Sewayojan etc.',
      'appbarItem1': 'About YUVASATHI ',
      'appbarItem2': 'Get Schemes ',
      'appbarItem3': 'Find Schemes',
      'appbarItem4': 'About PRD',
      'appbarItem5': 'FAQ',
      'appbarItem6': 'Forum',
      'appbarItem7': 'Press Releses',
      'appbarItem8': 'Photo Gallery',
      'appbarItem2SubItem1': 'About Yuva Sathi',
      'appbarItem2SubItem2': 'Get Schemes',
      'appbarItem2SubItem3': 'Benefits for Youth',
      'appbarItem3SubItem1': 'About Youth Welfare and Prantiya Rakshak Dal Department',
      'appbarItem5SubItem1': 'Press Release',
      'appbarItem5SubItem2': 'Photo Gallery',
      'startnow': 'Lets get started',
      'missPassword': 'Forget Password ?',
      'profile': 'Profile',
      'rateus': 'Rate Us',
      'logout': 'Logout',

      'searchtexthead1': 'Scheme Category',
      'searchtexthead2': 'By Government',
      'searchtexthead3': 'Department',
      'searchtextsubhead1': 'Select Scheme Category',
      'searchtextsubhead2': 'Select Government',
      'searchtextsubhead3': 'Select Department',
      'stateGov': 'State Government  ',
      'centralGov': 'Central Government ',
      'centralSpon': 'Centrally Sponsored ',
      'deaprtment1': 'Department 1',
      'deaprtment2': 'Department 2',
      'deaprtment3': 'Department 3',

      'search': 'Search',
      'details': 'Details',
      'iconSearchtextHeading': 'Search schemes by category',
      'address': 'Address',
      'inquiry': 'Inquiry',
      'sendmsg': 'Send Message',
      'fulladdress': 'Diretor General Youth Welfare and Prantiya Rakshak Dal Department Old Jail Road Anand Nagar Alambagh Lucknow 226005',

      'profitsteps1': 'All government schemes/services in one place',
      'profitsteps2': 'Smart Suggestions, Notifications, and alerts',
      'profitsteps3': 'A profile page for Youth where they can list their interest',
      'profitsteps4': 'Easy & quick platform to access related information',
      'profitsteps5': 'Quick and authentic information for Youth',
      'profitsteps6': 'News feeds & discussion forums',

      'aboutsubappbarh1': 'Yuva sathi a government initiative for youth of Uttar Pradesh to engage the youth with the benefits & information of govt. services/schemes in a single platform.',
      'aboutsubappbarh2': 'The portal work as an information hub to provide with a variety of information for the youth of Uttar Pradesh to connect with various government schemes/services, efforts and resources. It provides information on skill development programmes, employment opportunities, entrepreneurship & Start up development, scholarships Vocational Training, Self-Employment, Competitive Examination, Career Counselling, Sports, Health, etc. The youth portal is a platform where the youth of the state can access information & resources in one single platform to help them succeed in their personal and professional lives.',
      'mision': 'Mission',
      'vision': 'Vision',
      'aboutmision': 'The Yuva sathi portal aims to empower the youth of the state by providing them a right and relevant information to enhance their skills, knowledge and overall development.',
      'aboutvision': 'Our vision is to be an information hub for the youth; to connect the youth in one platform for their empowerment and development.',


      'whosubappbarh1': 'The Prantiya Rakshak Dal and Youth Welfare Department in Uttar Pradesh is a government initiative focused on empowering the youth. Through various schemes and programmes, it aims to enhance the overall development of young persons by providing opportunities for education, skill building and employment to shape a bright future for the youth of the state.',
      'whosubappbarh2': 'With the objective to improve overall development of the rural youths in the state, the Directorate has started following schemes:',
      'whosteps1': 'Creation of sports infrastructure and organisation of sports for enrichment of physical,mental and moral characte',
      'whosteps2': 'Organisation of cultural programmes to add rural youth in main stream.',
      'whosteps3': 'Empowerment of PRD and their Duty',
      'whosteps4': 'Awareness about public services.',

      'forumheading1': 'Top 10 Emerging Technologies That Will Shape the Future',
      'forumsubheading1': 'In today is fast-paced world, technology continues to advance at an astonishing rate, transforming various aspects of our lives. From healthcare to transportation, education to entertainment, emerging technologies are revolutionizing industries and reshaping the future. In this article, we will explore the top 10 emerging technologies that have the potential to make a significant impact in the years to come.',
      'forumconclution' :'These top 10 emerging technologies represent a glimpse into the future. As they continue to develop and mature, they will undoubtedly shape industries, transform economies, and redefine the way we live and work. From artificial intelligence and blockchain to robotics and clean energy',

      'forumtitlestep1': '1. Artificial Intelligence (AI) :',
      'forumtitlestep2': '2. Internet of Things (IoT):',
      'forumtitlestep3': '3. Blockchain:',
      'forumtitlestep4': '4. Quantum Computing:',
      'forumtitlestep5': '5. Augmented Reality (AR) and Virtual Reality (VR):',
      'forumtitlestep6': '6. 5G Technology:',
      'forumtitlestep7': '7. Biotechnology',
      'forumtitlestep8': '8. Robotics:',
      'forumtitlestep9': '9. Clean Energy Technologies:',
      'forumtitlestep10': '10. Nanotechnology:',
      'forumconclusionheading':'Conclusion',


      'forumdesstep1': 'Artificial Intelligence has already begun to permeate our lives, but its true potential is yet to be fully realized. AI-powered systems can analyze vast amounts of data, make predictions, and perform complex tasks, revolutionizing industries such as healthcare, finance, and manufacturing. As AI continues to evolve, we can expect advancements in machine learning, natural language processing, and robotics.',
      'forumdesstep2': 'Artificial Intelligence has already begun to permeate our lives, but its true potential is yet to be fully realized. AI-powered systems can analyze vast amounts of data, make predictions, and perform complex tasks, revolutionizing industries such as healthcare, finance, and manufacturing. As AI continues to evolve, we can expect advancements in machine learning, natural language processing, and robotics.',
      'forumdesstep3': 'Blockchain technology gained prominence with the rise of cryptocurrencies, but its potential extends far beyond digital currencies. Blockchain provides a secure and decentralized method for recording and verifying transactions, making it ideal for applications such as supply chain management, digital identities, and transparent voting systems.',
      'forumdesstep4': 'Quantum computing is poised to revolutionize computational power. By leveraging quantum mechanical phenomena, these powerful machines can solve complex problems exponentially faster than classical computers. Quantum computing holds promise for advancements in cryptography, optimization, and drug discovery.',
      'forumdesstep5': 'AR and VR technologies create immersive experiences that blend the virtual and physical worlds. Augmented Reality overlays digital information onto the real world, enhancing our perception, while Virtual Reality creates entirely simulated environments. These technologies have applications ranging from gaming and entertainment to education and training.',
      'forumdesstep6': 'As the successor to 4G, 5G technology promises faster speeds, lower latency, and greater capacity. With its increased bandwidth, 5G will enable the widespread adoption of technologies like autonomous vehicles, remote surgeries, and smart cities. This technology has the potential to revolutionize communication and connectivity on a global scale.',
      'forumdesstep7': 'Advancements in biotechnology are transforming healthcare and other industries. From gene editing and personalized medicine to biofuels and sustainable agriculture, biotechnology holds the promise of solving some of the most pressing challenges facing humanity.',
      'forumdesstep8': 'Robotics has made significant strides in recent years, and its impact is only growing. Robots are becoming more autonomous, capable of performing intricate tasks in various domains such as manufacturing, healthcare, and exploration. Collaborative robots (cobots) are also making their way into the workplace, working alongside humans to increase productivity and efficiency.',
      'forumdesstep9': 'As the world seeks sustainable alternatives to fossil fuels, clean energy technologies are gaining momentum. Solar power, wind energy, and energy storage solutions are becoming more efficient and affordable. The widespread adoption of clean energy will help mitigate climate change and reduce reliance on finite resources.',
      'forumdesstep10': 'Nanotechnology involves manipulating matter at the atomic and molecular scale. This technology has the potential to revolutionize various industries, including electronics, medicine, and materials science. With nanoscale innovations, we can develop more efficient batteries, targeted drug delivery systems, and ultra-strong materials.',

      'vibhag1': 'Directorate of Industries',
      'vibhag2': 'Infrastructure Development',
      'vibhag3': 'Skill Development and Entrepreneurship',
      'vibhag4': 'Skill Development and Entrepreneurship',

      'userdetail': 'User Details',
      'username': 'Your Name',
      'contactno': 'Contact No',
      'useremail': 'Your Email',
      'gender': 'Gender',
      'caste': 'Caste',
      'dob': 'Date of Birth',
      'service': 'Service',
      'empstatus': 'Emp.Status',
      'lastqualification': 'Last Qualification',
      'state': 'State',
      'district': 'District',
      'typrofarea': 'Type of Area',
      'addresss': 'Address',
      'editprofile':'Edit Profile',

      'up': 'Uttar Pradesh',
      'bihar': 'Bihar',
      'advancesearch': 'ADVANCE SEARCH',
      'searchscheme': 'Search Schemes',
      'svn': 'Search Schemes\n via Name',
      'svd': 'Search Schemes\n via Department',
      'svas': 'Advance\n Search',
      'svn_subtile': 'Enter Scheme Name',
      'schemescategory': 'Schemes Categories',
      'filters': 'Filters',
      'rating': 'Rating',
      'mode': 'Application Mode',
      'showpage': 'Showing 1 - 8 out of 8',
      'Sort by': '',
      'applyscheme': 'Apply for Scheme',

      'navbar1': 'Search Scheme',
      'navbar2': 'Call Support',
      'navbar3': 'Govt. Scheme',
      'navbar4': 'Profile',
      'filterresult': 'Filter Results By',
      'selectitem': 'Select an Items',
      'overview': 'Overview',
      'benifit': 'Benefits',
      'eligibility': 'Eligibility',
      'requirement': 'Requirements',
      'scheme': 'Schemes',
      'otpLogin': 'Login with OTP',
      'otpPassword': 'Login with Password ',
      'clickhere': ' Click Here',
      'online': 'Online',
      'offline': 'Offline',
      'onoffLine': 'Online-Offline',
      'both': 'Both',
      'remove': 'Remove Search',
      'noMoreScheme': 'No more Schemes in this category',
      'sendInquiryMsg': 'Thanks for contact',
      'logoutConfirm': 'Logout Confirmation',
      'logoutConfirmTitle': 'Are you sure you want to logout ?',
      'noMoreImg': 'No more Photos',
      'cancel': 'Cancel',
      'search1ifempty': 'We could not find any schemes.',
      'adminLogin': 'Admin Login',
      'adminLoginButton': 'Officer Login',
      'checkEligibility': 'Check Eligiblity',
      'completeProfileMsg': 'Please Complete Your Profile',
      'year': 'Year',
      'otpSendMsg': 'OTP sent successfully on mobile number',
      'noNotMatchMsg': 'Mobile number not found please check and try again',
      'eligibilitySuccessMsg': 'Congratulations, You are eligible for this scheme.',
      'pleasewait': 'Please Wait',
      'helpfulInfo': 'Was this information helpful?',
      'pleaseRateTitle': 'Please rate Yuva Sathi portal',
      'agreeT&C': 'I have obtained complete information related to the scheme on this Yuva Sathi portal, and I agree to visit the official website of this scheme to submit my application.',
      'T&C': 'I accept the terms and conditions',
      'changePassword': 'Change Password',
      'oldPassword': 'Old Password',
      'newPassword': 'New Password',
      'confirmPassword': 'Confirm Password',
      'updateProfile': 'Update Profile',
      'updatePassword': 'Update Password',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',

    },
    'hi_IN' : {

      'appbarTitle': 'युवा साथी',
      'gov_up': 'उत्तर प्रदेश सरकार',
      'welcom': 'आपका स्वागत है',
      'logobottom': 'सफलता का साथी युवा साथी !',
      'sanghtext': 'युवा कल्याण एवं \nप्रान्तीय रक्षक दल विभाग',
      'sanghtexts': 'युवा कल्याण एवं प्रान्तीय रक्षक दल विभाग',
      'exploremodule': 'मॉड्यूल का अन्वेषण करें',
      'appbarSecondTitle': 'युवा कल्याण से सम्बंधित योजनाओ की जानकारी प्राप्त कने हेतु अप्रमाणित स्रोतों पर न जाये | युवा साथी पोर्टल पर आज ही पंजीकरण करें और केवल अपने लिए लाभकारी योजनाओ के सम्बन्ध में आवश्यक जानकारी प्राप्त करे |',
      'backButton': 'पीछे जाये',
      'by': 'द्वारा',
      'step1': 'प्रथम चरण',
      'step2': 'दुत्तिय चरण',
      'step3': 'तृतीय चरण',
      'step4': 'चतुर्थ चरण',
      'step5': 'पंचम चरण',
      'step6': 'छठ चरण',
      'step7': 'सतम चरण',
      'step8': 'अंतिम चरण',

      'fcstep1': 'पंजीकरण के लिए युवाओं को मोबाइल नंबर दर्ज करना होगा |',
      'fcstep2': 'ओटीपी के माध्यम से सत्यापन',
      'fcstep3': 'युवाओं का प्रोफ़ाइल निर्माण',
      'fcstep4': 'युवाओं की बुनियादी जानकारी जैसे नाम, उम्र, लिंग, धर्म, जाति, वैवाहिक स्थिति, योग्यता, विशेषज्ञता, नौकरी की स्थिति, अनुभव, छात्रवृत्ति, पुरस्कार, आदि विवरण अंकित करे |',
      'fcstep5': 'युवा अपनी रुचि/कौशल का चयन करें और अपनी आवश्यकता अंकित करें |',
      'fcstep6': 'युवाओं को उनकी चयनित रुचि के अनुसार शासकीय योजनाओं के सम्बन्ध में सुझाव प्राप्त होंगे |',
      'fcstep7': 'युवाओं को योजनाओं/सेवाओं का लाभ प्राप्त करने के लिए आवेदन हेतु संबंधित विभाग के पोर्टल पर पुनर्निर्देशित किया जाएगा |',
      'fcstep8': 'विश्लेषणात्मक और एमआईएस रिपोर्ट राज्य सरकार को उपलब्ध कराई जाएगी |',

      'step1subheading': 'नाम और मोबाइल नंबर जैसे विवरण भरकर पंजीकरण करें | सत्यापन के लिए एक ओटीपी प्राप्त होगा।',
      'step2subheading': 'हमें अपने बारे में कुछ जानकारी प्रदान करें',
      'step3subheading': 'अपने चुने हुए कौशल के लिए योजना अनुशंसाएँ प्राप्त करें',
      'step4subheading': 'अपने अनुभव को निजीकृत करें. आगे बढ़ने के लिए अपना जिला चुनें',
      'step5subheading': 'आप किस जाति व्यवस्था से संबंध रखते हैं?',
      'step6subheading': 'अपने करियर परिदृश्य को मानचित्रित करने में सहायता करें',
      'step7subheading': 'अपने करियर परिदृश्य को मानचित्रित करने में हमारी सहायता करें',
      'step8subheading': '',
      'searchCardsubheading': 'सरकारी योजनाओं/सेवाओं को पोर्टल पर श्रेणीवार रूप में देखें',

      'profitsubappbarheading':'युवाओं का पंजीकरण उनकी आवश्यकता, रुचियों और कौशल के बारे में जानकारी प्राप्त करने और तदनुसार लाभ प्रदान करने के उद्देश्य से किया जाता है',
      'singupheading':'एक सरल पंजीकरण प्रक्रिया के माध्यम से अपनी आवश्यकताओं के लिए सर्वोत्तम योजनाओं का अवलोकन करें',
      'step1heading': 'एक सरल पंजीकरण प्रक्रिया के माध्यम से अपनी आवश्यकताओं के लिए सर्वोत्तम योजनाओं का अवलोकन करें',
      'step2heading': 'अपना परिचय दें !\nहम आपके बारे में और जानना चाहते हैं',
      'step3heading': 'जिन कौशलों में आपकी रुचि है, उनके लिए योजना की जानकारी प्राप्त करें',
      'step4heading': 'अपना स्थान चुनकर जिला-विशिष्ट विवरण प्राप्त करें',
      'step5heading': '',
      'step6heading': 'आपकी वर्तमान रोजगार स्थिति का पता लगाना',
      'step7heading': 'अपनी अंतिम योग्यता व्यक्त करें',
      'step8heading': 'अपनी पात्रता का अन्वेषण करें: उपलब्ध योजनाओं की खोज के लिए श्रेणियाँ चुनें',
      'searchCardheading': 'युवाओं से संबंधित विभिन्न विभागों की योजनाएं',

      'schemes1': 'शिक्षा और छात्रवृत्ति',
      'schemes2': 'व्यापार और उद्यमिता',
      'schemes3': 'कौशल विकास',
      'schemes4': 'खेल और संस्कृति',
      'schemes5': 'रोज़गार',
      'schemes6': 'अधिकारिता',
      'schemes7': 'आवास एवं आश्रय',
      'schemes8': 'वित्तीय सेवाएं',
      'schemes9': 'सामाजिक-आर्थिक',
      'schemes10': 'स्वास्थ्य और कल्याण',

      'warningtoast': 'विवरण उचित रूप से भरें',
      'rightsteptoast': 'आपका चरण सफल रहा',
      'loginSuccessptoast': 'लॉगिन सफल रहा',
      'successptoast': 'सफल रहा',
      'otpSuccessptoast': 'प्रमाणित सफल',
      'registerSuccessptoast': 'पंजीयन सफल',
      'getOTP': 'ओटीपी मिलने के बाद? ',
      'submittext': 'जमा करे',
      'resetPassword': 'पासवर्ड रीसेट करें',
      'other': 'अन्य',
      'tenth': '10 वीं कक्षा',
      'twelvth': '12 वीं कक्षा',
      'graduation': 'स्नातक',
      'pgraduation': 'स्नातकोत्तर',
      'next': 'अगला कदम',
      'step7SEThint': 'योग्यता का नाम दर्ज करें',
      'status1': 'कार्यरत',
      'status2': 'बेरोज़गार',
      'status3': 'स्वनियोजित',
      'status4': 'उद्यमी',
      'status5': 'विद्यार्थी',
      'sendotp': 'प्रमाणित करें',
      'register': 'पंजीयन करेंं',
      'registration': 'पंजीकरण करेंं',
      'noaccount': 'कोई खाता नहीं है? ',
      'ifregisterthenlogin': 'यदि पहले से पंजीकृत है तो लॉगिन करें ',
      'login': 'लॉगिन करें',
      'loginSmall': 'लॉगिन करें',
      'onlylogin': 'लॉगिन',
      'nameEditText': 'नाम दर्ज करें',
      'mobileEditText': 'मोबाइल नंबर दर्ज करें',
      'passwordEditText': 'पासवर्ड दर्ज करें',
      'emailEditText': 'ईमेल दर्ज करें',
      'subjectEditText': 'विषय दर्ज करें',
      'msgEditText': 'संदेश दर्ज करें',
      'cpasswordEditText': 'पासवर्ड की पुष्टि कीजिये',
      'otpEditText': 'सत्यापन कोड दर्ज करें',
      'otpNoText': 'आपके इस नंबर पर एक प्रमाणीकरण कोड भेजा जाएगा',
      'gender': 'लिंग',
      'male': 'पुरुष',
      'female': 'स्त्री',
      'age': 'उम्र',
      'ageEditText': 'उम्र दर्ज करें',
      'selectSkill': 'कौशल का चयन करें',
      'selectdistrict': 'जिला चुनें',
      'placeType': 'अपना स्थान प्रकार निर्दिष्ट करें',
      'rural': 'ग्रामीण',
      'arban': 'शहरी',
      'rl&rbn':'शहरी-ग्रामीण',
      'castEditText': 'जाति का नाम दर्ज करें',
      'cast1': 'जनरल वर्ग / सामान्य वर्ग',
      'cast2': 'ओबीसी / अन्य पिछड़ा वर्ग',
      'cast3': 'एस सी / अनुसूचित जाति',
      'cast4': 'एसटी / अनुसूचित जनजाति',
      'helpLineHeading': 'हम आपके सहयोग के लिए हमेशा उपलब्ध हैं! योजनाओं के बारे में विस्तृत जानकारी प्राप्त करने हेतु हमसे संपर्क करें',
      'helpLineSubHeading': 'हेल्प डेस्क नंबर  +91-9005604448',
      'footerHeading': 'उत्तर प्रदेश के युवाओं के लिए नौकरी, कौशल विकास, व्यावसायिक प्रशिक्षण, रोजगार, स्वरोजगार, उच्च शिक्षा, प्रतियोगी परीक्षा, कैरियर काउंसलिंग, खेल, स्वास्थ्य, माध्यमिक शिक्षा, स्टार्ट-अप, सेवायोजन आदि से संबंधित जानकारी प्राप्त करने के लिए एक एकल मंच।',
      'appbarItem1': 'युवा साथी के बारे में',
      'appbarItem2': 'योजनाएं प्राप्त करें',
      'appbarItem3': 'योजनाएं खोजें',
      'appbarItem4': 'पीआरडी के बारे में',
      'appbarItem5': 'सामान्य प्रश्न',
      'appbarItem6': 'फोरम',
      'appbarItem7': 'प्रेस विज्ञप्ति',
      'appbarItem8': 'फोटो गैलरी',
      'appbarItem2SubItem1': 'युवा साथी के बारे में',
      'appbarItem2SubItem2': 'युवा साथी के साथ पंजीकरण कैसे करें',
      'appbarItem2SubItem3': 'युवाओं के लिए लाभ',
      'appbarItem3SubItem1': 'युवा कल्याण एवं प्रांतीय रक्षक दल विभाग के बारे में',
      'appbarItem5SubItem1': 'प्रेस विज्ञप्ति',
      'appbarItem5SubItem2': 'फोटो गैलरी',
      'startnow': 'आएँ शुरू करें',
      'missPassword': 'पासवर्ड भूल गए ?',
      'profile': 'प्रोफ़ाइल',
      'rateus': 'रेटिंग ',
      'logout': 'लॉग आउट ',

      'searchtexthead1': 'योजना श्रेणी',
      'searchtexthead2': 'सरकार के द्वारा',
      'searchtexthead3': 'विभाग',
      'searchtextsubhead1': 'योजना श्रेणी का चयन करें',
      'searchtextsubhead2': 'सरकार का चयन करें',
      'searchtextsubhead3': 'विभाग का चयन करें',
      'stateGov': 'राज्य सरकार  ',
      'centralGov': 'केंद्र सरकार ',
      'centralSpon': 'केंद्र प्रायोजित ',
      'deaprtment1': 'विभाग 1',
      'deaprtment2': 'विभाग 2',
      'deaprtment3': 'विभाग 3',

      'search': 'खोजें',
      'details': 'विवरण',
      'iconSearchtextHeading': 'श्रेणी के आधार पर योजनाएं खोजें',
      'address': 'पता',
      'inquiry': 'पूछताछ',
      'sendmsg': 'सुरक्षित करे',
      'fulladdress': 'महानिदेशक युवा कल्याण एवं प्रांतीय रक्षक दल महा निदेशालय पुराना जेल रोड आनंद नगर आलमबाग लखनऊ 226005',

      'profitsteps1': 'सभी सरकारी योजनाएँ/सेवाएँ एक ही स्थान पर',
      'profitsteps2': 'सरकारी योजनाओं सम्बन्धी स्मार्ट सुझाव, सूचनाएं और अलर्ट',
      'profitsteps3': 'युवाओं के लिए एक प्रोफ़ाइल पृष्ठ जहां वे अपनी रुचि सूचीबद्ध कर सकते हैं',
      'profitsteps4': 'संबंधित जानकारी तक पहुंचने के लिए आसान और त्वरित मंच',
      'profitsteps5': 'युवाओं के लिए त्वरित एवं प्रामाणिक जानकारी',
      'profitsteps6': 'समाचार फ़ीड एवं चर्चा मंच',

      'aboutsubappbarh1': 'युवा साथी उत्तर प्रदेश के युवाओं के लिए एक नवीन पहल है जो युवाओं को सरकार द्वारा युवा कल्याण के लाभार्थ संचालित योजनाओ के सम्बन्ध में आवश्यक सूचना उपलब्ध कराएगी और एक ही मंच पर समस्त योजनाओ का लाभ प्राप्त करने हेतु आवेदन कर सकेगा।',
      'aboutsubappbarh2': 'यह पोर्टल उत्तर प्रदेश के युवाओं को विभिन्न सरकारी योजनाओं / सेवाओं यथा , कौशल विकास कार्यक्रमों, रोजगार के अवसरों, उद्यमिता और स्टार्ट अप विकास, छात्रवृत्ति व्यावसायिक प्रशिक्षण, स्व-रोज़गार, प्रतियोगी परीक्षा, कैरियर परामर्श, खेल, स्वास्थ्य आदि प्रयासों और संसाधनों से जोड़ने एवं विभिन्न प्रकार की जानकारी प्रदान करने के लिए एक सूचना केंद्र के रूप में काम करता है। युवा पोर्टल एक ऐसा मंच है जहां राज्य के युवा अपने व्यक्तिगत और व्यावसायिक जीवन में सफल होने के लिए एक ही मंच पर सूचना और संसाधनों तक पहुंच सकते हैं।',
      'mision': 'उद्देश्य',
      'vision': 'दृष्टि',
      'aboutmision': 'युवा साथी पोर्टल का उद्देश्य राज्य के युवाओं को उनके कौशल, ज्ञान और समग्र विकास को बढ़ाने के लिए सही और प्रासंगिक जानकारी प्रदान करके सशक्त बनाना है।',
      'aboutvision': 'हमारा लक्ष्य युवाओं के सशक्तिकरण और विकास के लिए सूचना केंद्र बनना है।',

      'whosubappbarh1': 'उत्तर प्रदेश में प्रांतीय रक्षक दल और युवा कल्याण विभाग एक सरकारी पहल है जो युवाओं को सशक्त बनाने पर केंद्रित है। विभिन्न योजनाओं और कार्यक्रमों के माध्यम से, इसका उद्देश्य राज्य के युवाओं के लिए एक उज्जवल भविष्य को आकार देने के लिए शिक्षा, कौशल निर्माण और रोजगार के अवसर प्रदान करके युवा व्यक्तियों के समग्र विकास को बढ़ाना है।',
      'whosubappbarh2': 'ग्रामीण युवाओ के समग्र विकास के लिए निदेशालय द्वारा निम्नलिखित योजनाये संचालित की जा रही है :',
      'whosteps1': 'खेल कूद हेतु अवस्थापना सुविधाओ का सृजन एवं ग्रामीण युवको के शारीरिक, मानसिक और नैतिक चरित्र का खेल कूद का आयोजन के माध्यम से विकास |',
      'whosteps2': 'ग्रामीण युवको को मुख्य धारा से जोड़ने के लिए सांस्क्रतिक कार्यक्रमों का आयोजन |',
      'whosteps3': 'प्रांतीय रक्षक दल का सशक्तिकरण |',
      'whosteps4': 'जनसेवाओ के सम्बन्ध में जागरूकता |',

      'forumheading1': 'शीर्ष 10 उभरती प्रौद्योगिकियाँ जो भविष्य को आकार देंगी',
      'forumsubheading1': 'आज की तीव्रगति से परिवर्तनशील दुनिया में, प्रौद्योगिकी आश्चर्यजनक दर से आगे बढ़ रही है और हमारे जीवन के विभिन्न पहलुओं को बदल रही है। स्वास्थ्य सेवा से लेकर परिवहन, शिक्षा से लेकर मनोरंजन तक, उभरती प्रौद्योगिकियाँ उद्योगों में क्रांति ला रही हैं और भविष्य को नया आकार दे रही हैं। इस लेख में, हम शीर्ष 10 उभरती प्रौद्योगिकियों का विवरण दिया गया है जिनमें आने वाले वर्षों में महत्वपूर्ण प्रभाव डालने की क्षमता है।',
      'forumconclution': 'ये शीर्ष 10 उभरती प्रौद्योगिकियां भविष्य की एक झलक पेश करती हैं। जैसे-जैसे वे विकसित और परिपक्व होते रहेंगे, वे निस्संदेह उद्योगों को आकार देंगे, अर्थव्यवस्थाओं को बदल देंगे और हमारे जीने और काम करने के तरीके को फिर से परिभाषित करेंगे। कृत्रिम बुद्धिमत्ता और ब्लॉकचेन से लेकर रोबोटिक्स और स्वच्छ ऊर्जा तक !',

      'forumtitlestep1': '1. आर्टिफिशियल इंटेलिजेंस (एआई) :',
      'forumtitlestep2': '2. इंटरनेट ऑफ थिंग्स (IoT):',
      'forumtitlestep3': '3. ब्लॉकचेन:',
      'forumtitlestep4': '4. क्वांटम कंप्यूटिंग:',
      'forumtitlestep5': '5. संवर्धित वास्तविकता (एआर) और आभासी वास्तविकता (वीआर):',
      'forumtitlestep6': '6. 5G तकनीक :',
      'forumtitlestep7': '7. जैव प्रौद्योगिकी:',
      'forumtitlestep8': '8. रोबोटिक्स:',
      'forumtitlestep9': '9. स्वच्छ ऊर्जा प्रौद्योगिकी:',
      'forumtitlestep10': '10. नैनोटेक्नोलॉजी:',
      'forumconclusionheading':'निष्कर्ष',

      'forumdesstep1': 'आर्टिफिशियल इंटेलिजेंस ने पहले ही हमारे जीवन में प्रवेश करना शुरू कर दिया है, लेकिन इसकी वास्तविक क्षमता का अभी तक पूरी तरह से एहसास नहीं हुआ है। एआई-संचालित सिस्टम बड़ी मात्रा में डेटा का विश्लेषण कर सकते हैं, भविष्यवाणियां कर सकते हैं और जटिल कार्य कर सकते हैं, जिससे स्वास्थ्य देखभाल, वित्त और विनिर्माण जैसे उद्योगों में क्रांति आ सकती है। जैसे-जैसे एआई का विकास जारी है, हम मशीन लर्निंग, प्राकृतिक भाषा प्रसंस्करण और रोबोटिक्स में प्रगति की उम्मीद कर सकते हैं।',
      'forumdesstep2': 'इंटरनेट ऑफ थिंग्स का तात्पर्य परस्पर जुड़े उपकरणों के नेटवर्क से है जो डेटा एकत्र और विनिमय कर सकता है। IoT तकनीक उपकरणों के बीच निर्बाध संचार को सक्षम बनाती है और स्मार्ट घरों, कनेक्टेड शहरों और कुशल औद्योगिक प्रक्रियाओं के लिए संभावनाएं खोलती है। स्मार्ट थर्मोस्टेट से लेकर पहनने योग्य उपकरणों तक, IoT हमारे परिवेश के साथ बातचीत करने के तरीके को बदल रहा है।',
      'forumdesstep3': 'क्रिप्टोकरेंसी के उदय के साथ ब्लॉकचेन तकनीक को प्रमुखता मिली, लेकिन इसकी क्षमता डिजिटल मुद्राओं से कहीं आगे तक फैली हुई है। ब्लॉकचेन लेनदेन को रिकॉर्ड करने और सत्यापित करने के लिए एक सुरक्षित और विकेन्द्रीकृत तरीका प्रदान करता है, जो इसे आपूर्ति श्रृंखला प्रबंधन, डिजिटल पहचान और पारदर्शी मतदान प्रणाली जैसे अनुप्रयोगों के लिए आदर्श बनाता है।',
      'forumdesstep4': 'क्वांटम कंप्यूटिंग कम्प्यूटेशनल शक्ति में क्रांति लाने के लिए तैयार है। क्वांटम यांत्रिक घटनाओं का लाभ उठाकर, ये शक्तिशाली मशीनें पुराने कंप्यूटरों की तुलना में जटिल समस्याओं को तेजी से हल कर सकती हैं। क्वांटम कंप्यूटिंग क्रिप्टोग्राफी, अनुकूलन और दवा खोज में प्रगति का वादा करती है।',
      'forumdesstep5': 'एआर और वीआर प्रौद्योगिकियां गहन अनुभव पैदा करती हैं जो आभासी और भौतिक दुनिया को मिश्रित करती हैं। संवर्धित वास्तविकता वास्तविक दुनिया पर डिजिटल जानकारी को लागू करती है, हमारी धारणा को बढ़ाती है, जबकि आभासी वास्तविकता पूरी तरह से अनुरूपित वातावरण बनाती है। इन प्रौद्योगिकियों में गेमिंग और मनोरंजन से लेकर शिक्षा और प्रशिक्षण तक के अनुप्रयोग हैं।',
      'forumdesstep6': '4जी के उत्तराधिकारी के रूप में, 5जी तकनीक तेज गति, कम विलंबता और अधिक क्षमता का वादा करती है। अपनी बढ़ी हुई बैंडविड्थ के साथ, 5G स्वायत्त वाहनों, रिमोट सर्जरी और स्मार्ट शहरों जैसी प्रौद्योगिकियों को व्यापक रूप से अपनाने में सक्षम करेगा। इस तकनीक में वैश्विक स्तर पर संचार और कनेक्टिविटी में क्रांति लाने की क्षमता है।',
      'forumdesstep7': 'जैव प्रौद्योगिकी में प्रगति स्वास्थ्य देखभाल और अन्य उद्योगों को बदल रही है। जीन संपादन और व्यक्तिगत चिकित्सा से लेकर जैव ईंधन और टिकाऊ कृषि तक, जैव प्रौद्योगिकी मानवता के सामने आने वाली कुछ सबसे गंभीर चुनौतियों को हल करने का वादा करती है।',
      'forumdesstep8': 'रोबोटिक्स ने हाल के वर्षों में महत्वपूर्ण प्रगति की है, और इसका प्रभाव केवल बढ़ रहा है। रोबोट अधिक स्वायत्त होते जा रहे हैं, जो विनिर्माण, स्वास्थ्य सेवा और अन्वेषण जैसे विभिन्न क्षेत्रों में जटिल कार्य करने में सक्षम हैं। सहयोगी रोबोट (कोबोट) भी कार्यस्थल में अपना रास्ता बना रहे हैं, उत्पादकता और दक्षता बढ़ाने के लिए मनुष्यों के साथ काम कर रहे हैं।',
      'forumdesstep9': 'जैसे-जैसे दुनिया जीवाश्म ईंधन के स्थायी विकल्प तलाश रही है, स्वच्छ ऊर्जा प्रौद्योगिकियाँ गति पकड़ रही हैं। सौर ऊर्जा, पवन ऊर्जा और ऊर्जा भंडारण समाधान अधिक कुशल और किफायती होते जा रहे हैं। स्वच्छ ऊर्जा को व्यापक रूप से अपनाने से जलवायु परिवर्तन को कम करने और सीमित संसाधनों पर निर्भरता कम करने में मदद मिलेगी।',
      'forumdesstep10': 'नैनोटेक्नोलॉजी में परमाणु और आणविक पैमाने पर पदार्थ में हेरफेर करना शामिल है। इस तकनीक में इलेक्ट्रॉनिक्स, चिकित्सा और सामग्री विज्ञान सहित विभिन्न उद्योगों में क्रांति लाने की क्षमता है। नैनोस्केल नवाचारों के साथ, हम अधिक कुशल बैटरी, लक्षित दवा वितरण प्रणाली और अल्ट्रा-मजबूत सामग्री विकसित कर सकते हैं।',

      'vibhag1': 'उद्योग एवं उद्यम संवर्धन',
      'vibhag2': 'औद्योगिक विकास एवं अवसंरचना विभाग',
      'vibhag3': 'कौशल विकास और उद्यमिता मंत्रालय',
      'vibhag4': 'कौशल विकास और उद्यमिता मंत्रालय',

      'userdetail': 'उपयोगकर्ता विवरण',
      'username': 'आपका नाम',
      'contactno': 'संपर्क नंबर',
      'useremail': 'आपका ईमेल',
      'gender': 'लिंग',
      'caste': 'जाति',
      'dob': 'जन्म की तारीख',
      'service': 'सेवा',
      'empstatus': 'रोज़गार की स्थिति',
      'lastqualification': 'अंतिम योग्यता',
      'state': 'राज्य',
      'district': 'ज़िला',
      'typrofarea': 'क्षेत्र का प्रकार',
      'addresss': 'पता',
      'editprofile': 'प्रोफ़ाइल संपादित करें',
      'up': 'उत्तर प्रदेश',
      'bihar': 'बिहार',

      'advancesearch': 'उन्नत खोज',
      'searchscheme': 'योजनाएं खोजें',
      'svn': 'नाम के माध्यम\n से योजनाएं खोजें',
      'svd': 'विभाग के माध्यम\n से योजनाएं खोजें',
      'svas': 'उन्नत\n खोज',
      'svn_subtile': 'योजना का नाम दर्ज करें',
      'schemescategory': 'योजनाएँ श्रेणियाँ',

      'filters': 'फिल्टर',
      'rating': 'रेटिंग',
      'mode': 'आवेदन मोड',
      'showpage': '8 में से 1 - 8 दिखा रहा हूँ',

      'applyscheme': 'योजना के लिए आवेदन करें',
      'navbar1': 'खोज योजना',
      'navbar2': 'सहायता को कॉल करें',
      'navbar3': 'सरकार. योजना',
      'navbar4': 'प्रोफ़ाइल',
      'filterresult': 'परिणाम फ़िल्टर करें',
      'selectitem': 'कृपया आइटम चुनें',
      'overview': 'योजना का विवरण',
      'benifit': 'लाभ',
      'eligibility': 'पात्रता',
      'requirement': 'आवश्यकताएं',
      'scheme': 'योजनाएँ',
      'otpLogin': 'ओटीपी से लॉगिन करें ',
      'otpPassword': 'पासवर्ड से लॉगिन करें',
      'clickhere': ' यहाँ क्लिक करें',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन',
      'onoffLine': 'ऑनलाइन-ऑफलाइन',
      'both': 'दोनों',
      'remove': 'खोज बंद करे',
      'noMoreScheme': 'इस श्रेणी में कोई और योजना नहीं है',
      'sendInquiryMsg': 'संपर्क के लिए धन्यवाद',
      'logoutConfirm': 'लॉगआउट पुष्टिकरण',
      'logoutConfirmTitle': 'क्या आप लॉग आउट करना चाहते हैं ?',
      'noMoreImg': 'कोई और फ़ोटो नहीं',
      'cancel': 'रद्द करे',
      'search1ifempty': 'हमें कोई स्कीम नहीं मिली.',
      'adminLogin': 'व्यवस्थापक लॉगिन',
      'adminLoginButton': 'अफ़सर लॉगिन',
      'checkEligibility': 'पात्रता जांचें',
      'completeProfileMsg': 'कृपया अपना प्रोफ़ाइल पूरा करें',
      'year': 'वर्ष',
      'otpSendMsg': 'OTP सफलतापूर्वक मोबाइल नंबर पर भेजा गया है।',
      'noNotMatchMsg': 'मोबाइल नंबर नहीं मिला कृपया जांचें और पुनः प्रयास करें',
      'eligibilitySuccessMsg': 'बधाई हो, आप इस योजना के लिए पात्र हैं।',
      'pleasewait': 'कृपया प्रतीक्षा करें',
      'helpfulInfo': 'योजना उपयोगी है या नहीं इसकी जानकारी?',
      'pleaseRateTitle': 'कृपया युवा साथी पोर्टल को रेटिंग दें',
      'agreeT&C': 'मैं इस युवा साथी पोर्टल पर योजना से संबंधित सम्पूर्ण जानकारी प्राप्त कर चुका हूँ, और मैं इस योजना की आधिकारिक वेबसाइट पर जाकर अपने आवेदन के हेतु सहमत हूँ।',
      'T&C': 'मुझे नियम और शर्तें स्वीकार हैं',
      'changePassword': 'पासवर्ड बदलें',
      'oldPassword': 'पुराना पासवर्ड',
      'newPassword': 'नया पासवर्ड',
      'confirmPassword': 'पासवर्ड की पुष्टि कीजिये',
      'updateProfile': 'अपडेट प्रोफ़ाइल',
      'updatePassword': 'अपडेट पासवर्ड',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
      'schemes': '',
    }

  };

}